# print(dir())
str1 = 'ab'
seq1 = ["1","2","3"]
# print(str1.isalpha())
# print(str1.isdecimal())
# print(str1.islower())
# print(str1.isupper())
# print(str1.startswith(("o","h")))
# print(str1.endswith("h"))
# print(str1.index("h"))
# print(str1.rindex("h"))
# print(str1.find(("j")))
# print(str1.rfind())
# str2 = str1.replace("h","h")
# print(str1.partition("l"))
# print(str1.rpartition("l"))
# print(str1.split())
# import re
# print(re.split("(\W)",str1))
# print(str1.splitlines(1))
# print(str1.join(seq1))
# print(str1.lower())
# str2=str1.lower()
# print(str2)
# print(id(str1),id(str2))
# print(str1.upper())
# print(str1.ljust(2))
# print(str1.rjust(3))
# print(str1.center(3,"n"))
# print(str1.strip("abc") == "")
# print(str1)
# print(str1.lstrip())
# print(str1.rstrip())

# print(str1.capitalize())
# print(str1.casefold())
# print(str1.count())
# print(str1.encode())
# print(str1.expandtabs())
# print(str1.format())
# print(str1.format_map())
# print(str1.rsplit())
# print(str1.rstrip())
# print(str1.swapcase())
# print(str1.title())
# print(str1.translate())
# print(str1.zfill())